### ISSUE TITLE
[Wizard]: throws console error propertyValidator.attributeToProperty is not a function

### ISSUE THREAD

**Issue by sebastian-kraemer** [SAP/ui5-webcomponents#7198]
### Describe the bug

When using the Wizard component, the following error is thrown in the console:

Uncaught TypeError: propertyValidator.attributeToProperty is not a function
    at HTMLElement.attributeChangedCallback (UI5Element.ts:505:42)
    at UI5Element.ts:353:28
    at Array.map (<anonymous>)
    at Dialog._updateSlots (UI5Element.ts:315:43)
    at Dialog._processChildren (UI5Element.ts:288:15)
    at Dialog.connectedCallback (UI5Element.ts:192:15)
    at HTMLHtmlElement.<anonymous> (cypress_runner.js:102681:12)
    at domManip (cypress_runner.js:102519:14)
    at jQuery.fn.init.append (cypress_runner.js:102678:10)
    at AutIframe.restoreDom (index-08193975.js:111324:38)

### Isolated Example

https://codesandbox.io/p/sandbox/silly-fast-4f89c9

### Reproduction steps

1. See console errors

### Expected Behaviour

No console error

### UI5 Web Components for React Version

1.16.1

### UI5 Web Components Version

1.14.0

### Browser

Chrome, Edge

### Operating System

Windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 
There is an issue with the Wizard component when used with `content-layout="MultipleSteps"` in the latest version.
Latest version: https://codesandbox.io/s/ui5-webcomponents-forked-qcwwjt?file=/index.html
Works in 1.11: https://codesandbox.io/s/ui5-webcomponents-forked-kdfj7h?file=/index.html
Since the component crashes, thus preventing upgrading an app to a higher version of the library, I think this issue is fit for High priority.
There is also something missing from the playground docs on the stable version, but it is available on the latest build. See the above comment.

Would you please take a look?
