### ISSUE TITLE
[SF][CheckboxTemplate/JSX-runtime]:  Cannot find module '@ui5/webcomponents-base/jsx-runtime' error on version 2.6.0

### ISSUE THREAD

**Issue by Ankitadoshi** [SAP/ui5-webcomponents#10744]
### Bug Description

When we upgrade webcomponents to 2.6.X version, and run the build or unit test cases we are getting error as below:
This is happening for multiple components that uses List or table with Multiselect selection mode.
This is a high priority issue for us since we need 2.6.x version to implement the drag and drop feature for our project.

**Component Versions:**
    "@ui5/webcomponents": "^2.6.0",
    "@ui5/webcomponents-compat": "~2.6.0",
    "@ui5/webcomponents-base": "^2.6.0",
    "@ui5/webcomponents-fiori": "^2.6.0",
    "@ui5/webcomponents-icons": "^2.4.0",
    "@ui5/webcomponents-localization": "~2.4.0",
    "@ui5/webcomponents-react": "^2.6.0",
    "@ui5/webcomponents-react-compat": "^2.6.0",

**While running test cases:**
Cannot find module '@ui5/webcomponents-base/jsx-runtime' from 'node_modules/@ui5/webcomponents/dist/CheckBoxTemplate.js'
    Require stack:
      node_modules/@ui5/webcomponents/dist/CheckBoxTemplate.js
      node_modules/@ui5/webcomponents/dist/CheckBox.js
      node_modules/@ui5/webcomponents-react/dist/webComponents/CheckBox/index.js
      node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/pluginHooks/useRowDisableSelection.js
      node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/pluginHooks/AnalyticalTableHooks.js
      node_modules/@ui5/webcomponents-react/dist/index.js
      src/utils/pickListFilterUtils.js
      src/store/middleware/filtersSlice.js
      src/Components/Filters/Filters.js
      src/Components/Filters/Filters.test.js

**While building:**
Failed to parse source map from '/Users/I523602/Desktop/dev/src/recruiting-applicationlist/node_modules/@ui5/webcomponents-base/dist/prod/thirdparty/preact/jsxRuntime.module.js.map' file: Error: ENOENT: no such file or directory, open '/Users/I523602/Desktop/dev/src/recruiting-applicationlist/node_modules/@ui5/webcomponents-base/dist/prod/thirdparty/preact/jsxRuntime.module.js.map'

Can you please let us know on how to resolve these errors?

### Affected Component

SF

### Expected Behaviour

The test cases and the build should should pass without any issues

### Steps to Reproduce

1. Upgrade to web components 2.6.0
2. Run npm install
3. Run unit test cases or buils
...

### Priority

High

### UI5 Web Components Version

2.6.0

### Browser

Chrome

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
The error when building (missing .js.map) is fixed with https://github.com/SAP/ui5-webcomponents/pull/10596
and available in the latest RC https://github.com/SAP/ui5-webcomponents/releases/tag/v2.7.0-rc.2
2.7 will be released this week.

The error in the tests is somewhat different, can't really tell without further info. Can you try if 2.7.0-rc.2 fixes both errors and let me know?

**Comment by Ankitadoshi** [comment]
Hi @pskelin 
Yes post upgrading to 2.7.0, the issue with the build (missing .js.map) is resolved.

But our test cases are still failing. Seems like there are two issues:

1) As per my analysis this seems to be a path problem for jsx-runtime file.
We see that multiple JS like ***template.js are present for various components in the webcomponents/dist folder once we do npm install 
These template files all have import for jsx-runtime. For example in CheckboxTemplate.js first line.
import { jsx as _jsx, jsxs as _jsxs } from "@ui5/webcomponents-base/jsx-runtime";
And if i check the @ui5/webcomponents-base package, the jsx-runtime is present in the dist folder so i feel that these import needs to be changed from 
```
import { jsx as _jsx, jsxs as _jsxs } from "@ui5/webcomponents-base/jsx-runtime"; 
to 
import { jsx as _jsx, jsxs as _jsxs } from "@ui5/webcomponents-base/dist/jsx-runtime";
```

2) Another issue is from the React Wrapper(ui5-webcomponents-react) as I can see the imports are not correctly added there as well 
https://github.com/SAP/ui5-webcomponents-react/blob/d68bd2c7ddc6848dc81655742f3fdbb622078dd9/packages/base/src/utils/index.ts
Here as well the path does not have dist/
Currently it is import { getEffectiveScopingSuffixForTag } from '@ui5/webcomponents-base/CustomElementsScope.js';
But the actual file is present inside dist folder so the import path should be
import { getEffectiveScopingSuffixForTag } from '@ui5/webcomponents-base/dist/CustomElementsScope.js';

Not sure if we are missing any configurations here. 
Please let me know if more information is needed

**Comment by ilhan007** [comment]
In the @ui5/webcomponents-base [package.json](https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/package.json#L20) we have this configuration that is supposed to handle the 
import to "@ui5/webcomponents-base/jsx-runtime":

```json

"exports": {
    "./jsx-runtime": "./dist/jsx-runtime.js",
    "./jsx-dev-runtime": "./dist/jsx-dev-runtime.js",
     ...
```

And for the second:
```ts
import { getEffectiveScopingSuffixForTag } from '@ui5/webcomponents-base/CustomElementsScope.js';
```
we do reexport of a lot of modules ( including CustomElementsScope) via this [index.js](https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/index.js#L59) file.

I suggest we get in contact offline to get the project running..

**Comment by Ankitadoshi** [comment]
Hi @ilhan007 
Please let me know if there is any updates here. This is high priority for us since without this upgrade, We cannot take up drag and drop feature which is must have for our release

Thanks,
Ankita

**Comment by ilhan007** [comment]
Update 1:

Failure 1:

**Cannot find module '@ui5/webcomponents-base/CustomElementsScope.js' from 'node_modules/@ui5/webcomponents-react-base/dist/utils/index.js**
this is [fixed](https://github.com/SAP/ui5-webcomponents-react/pull/6901/files) and released with @ui5/webcomponents-react 2.7.1. I have updated your project locally to test the fix and the this failure stopped.
----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----  ----- ----- ----- -----

Failure 2:

The next problem then appeared
**Cannot find module '@ui5/webcomponents-base/jsx-runtime' from 'node_modules/@ui5/webcomponents/dist/CheckBoxTemplate.js'**
Seems the reexports are not working fine with jest (all issues happen only in tests),
so I have configured this mapping in the package.json under the "jest":
"moduleNameMapper": {
      "^@ui5/webcomponents-base/jsx-runtime$": "<rootDir>/node_modules/@ui5/webcomponents-base/dist/jsx-runtime.js"
},
This resolves the problem
----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----  ----- ----- ----- -----

Failure 3:
Then, I faced next problem with the tests
  **TypeError: Cannot read properties of undefined (reading 'states')
      at Button._setBadgeOverlayStyle (node_modules/@ui5/webcomponents/src/Button.ts:379:20)**
This is a known problem, jest does not support a lot of browser native APIs, and recently we added code to the Button that uses ElementInternals API (which is standard browser API), but not supported in jest. However, to make jest users happy we already merged this fix
https://github.com/SAP/ui5-webcomponents/pull/10782 taht provides a shim for the missing native API in jest.

**Comment by ilhan007** [comment]
Update 2:

We have released 2.7.1 for all packages on the public npm (including the aforementioned ElementInternals shim for jest/jsdom env), but not available on the internal registry https://int.repositories.cloud.sap/artifactory/api/

Once available:
- Update your package.json, clean node_modules, and install 2.7.1 for all @ui5/* packages (see the screenshot)
- Add the moduleNameMapper setting in your package.json under jest (see the screenshot)
- Use the ssr-sdom-shim module
You have to import it only for the tests, before importing the components you test. I am not sure if there is some entry point for the tests, or you will need to add it to all .test.js files, but this is the module that implements shims for missing browser native APIs in jest (jsdom)
```ts
import @ui5/webcomponents-base/dist/ssr-dom-shim.js
```

**Comment by ilhan007** [comment]
The issue has been resolved with the suggested changes in the application.

**Comment by codefactor** [comment]
@ilhan007 ,
I am getting this error in jest tests on my module"
```
Cannot find module '@ui5/webcomponents-base/jsx-runtime'  ....
```

This is mentioned as failure 2 - have you fixed this issue?  The hack to the package.json should not be necessary to alias a module like this - but i does unblock me.

**Comment by Greg-Owens** [comment]
This is not just a jest problem I think...  I am developing in MeteorJS and getting the same error message - no jest in use...  I cannot use any ui5 webcomponents

**Comment by Greg-Owens** [comment]
I am running 2.7.2

**Comment by eskimoblood** [comment]
Same here, we are suing cypress component tests and got this error message when try to update to 2.8.0

```
TypeError: The following error originated from your test code, not from Cypress.

  > Failed to resolve module specifier "@ui5/webcomponents-base/jsx-runtime". Relative references must start with either "/", "./", or "../".

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

**Comment by pskelin** [comment]
Hi,
the import `@ui5/webcomponents-base/jsx-runtime` is specified in `base/package.json` and all modern build tools should resolve it to
https://github.com/SAP/ui5-webcomponents/blob/d3580adacf83d7fa636927f6e6c3b0d20df50d27/packages/base/package.json#L20

What is your cypress setup? Usually in a new project, cypress is using vite and it has support for resolving such references. Jest (and meteor mentioned above) use some really old build tools that do not support conditional exports that are a pretty standard feature nowadays.

So can you share your cypress version and setup? Perhaps update to the latest cypress?

**Comment by eskimoblood** [comment]
We use cypress 14.1.0 so mostly up to date. But we use an older version of rollup

here is our setup:
```
import { nodeResolve } from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import dynamicImportVars from '@rollup/plugin-dynamic-import-vars'
import typescript from 'rollup-plugin-typescript2'
import postcss from 'rollup-plugin-postcss'
import dotenv from 'rollup-plugin-dotenv'
import poFileLoader from './rollup_plugins/poFileLoader'
import path from 'path'
import { globSync } from 'glob'

const { babel } = require('@rollup/plugin-babel')

export default {
    input: [
        './cypress/support/component.ts',
        ...globSync(path.resolve(__dirname, 'src/**/*.cy.*'), {
            ignore: '**/node_modules/**',
        }),
    ],
    output: {
        dir: `./cypress/dist`,
        format: 'esm',
        entryFileNames: '[name].js',
        chunkFileNames: '[name].[hash].js',
        sourcemap: true,
    },
    plugins: [
        nodeResolve({ preferBuiltins: false, browser: true }),
        babel({ babelHelpers: 'bundled', exclude: 'node_modules/**' }),
        commonjs(),
        postcss({
            modules: true,
            inject: true,
        }),
        typescript({
            tsconfigOverride: {
                include: [
                    'src/**/*',
                    'cypress.rollup.config.ts',
                    'cypress/support/*',
                ],
                compilerOptions: {
                    declaration: false,
                    declarationDir: 'dts',
                    types: [
                        'cypress',
                        '@ui5/webcomponents-cypress-commands',
                        '@testing-library/cypress',
                    ],
                },
            },
        }),
        poFileLoader(),
        dynamicImportVars(),
        dotenv(),
    ],
    external: [],
}
```

**Comment by wilson-xu-sap** [comment]
Hi @ilhan007 I used to try this method to make tests run, however, this error occurs in main project in 2.10.0.

<img width="529" alt="Image" src="https://github.com/user-attachments/assets/4bfbfe16-9138-4fc8-bc20-2bc66631bfdd" />

> Update 2:
> 
> We have released 2.7.1 for all packages on the public npm (including the aforementioned ElementInternals shim for jest/jsdom env), but not available on the internal registry https://int.repositories.cloud.sap/artifactory/api/
> 
> Once available:
> 
> * Update your package.json, clean node_modules, and install 2.7.1 for all @ui5/* packages (see the screenshot)
> * Add the moduleNameMapper setting in your package.json under jest (see the screenshot)
> * Use the ssr-sdom-shim module
>   You have to import it only for the tests, before importing the components you test. I am not sure if there is some entry point for the tests, or you will need to add it to all .test.js files, but this is the module that implements shims for missing browser native APIs in jest (jsdom)
> 
> import "ui5/webcomponents-base/dist/ssr-dom-shim.js";

**Comment by ilhan007** [comment]
Hello @Ankitadoshi can you check if the solution below works for you 
(as far as I got the issues are coming from the same project)
https://github.com/SAP/ui5-webcomponents/issues/11745#issuecomment-2991578738
