### ISSUE TITLE
[localization]: DateFormat error for MM/DD/YYYY pattern

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#7670]
### Bug Description

After upgrading from version 1.15.1 to 1.17.0 we are getting an error when using DateFormat with the "MM/DD/YYYY" pattern.

It works for other formats such a "d/MMM/yyyy".

### Affected Component

DateFormat

### Expected Behaviour

There should be no error when using a common date pattern

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-ks6s29

### Steps to Reproduce

1. Go to sample sandbox (https://codesandbox.io/s/ui5-webcomponents-forked-ks6s29)
2. Click the button "click to see error"
3. Notice an error is thrown

### Log Output, Stack Trace or Screenshots

Error with stack trace:
```
(0 , Configuration.default).getCalendarWeekNumbering is not a function
    at UniversalDate.getWeekByDate (https://ks6s29.csb.app/node_modules/
ui5/webcomponents-localization/dist/sap/ui/core/date/UniversalDate.js:143:81
    at UniversalDate.getUTCWeek (https://ks6s29.csb.app/node_modules/
ui5/webcomponents-localization/dist/sap/ui/core/date/UniversalDate.js:105:24
    at Object.format (https://ks6s29.csb.app/node_modules/
ui5/webcomponents-localization/dist/sap/ui/core/format/DateFormat.js:595:25
    at DateFormat._format (https://ks6s29.csb.app/node_modules/
ui5/webcomponents-localization/dist/sap/ui/core/format/DateFormat.js:1371:41
    at DateFormat.format (https://ks6s29.csb.app/node_modules/
ui5/webcomponents-localization/dist/sap/ui/core/format/DateFormat.js:1442:20
```

### Priority

Very High

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 
This issue is related with the UniversalDate module from the localization package.
I understand it is currently stopping a dependency upgrade for SuccessFactors. There is a reproducible sample.

Would you have a look?

**Comment by ee92** [comment]
"MM/DD/YYYY" is not a valid date pattern. We have fixed the issue at the application layer, so I'll close this ticket. Thanks!
