### ISSUE TITLE
[ui5-dialog]: Dialog.show leads to a TypeError exception

### ISSUE THREAD

**Issue by louologuem** [SAP/ui5-webcomponents#7070]
### Bug Description

After an upgrade (of `@ui5/webcomponents`) to  `v1.13.0` we're are seeing some of our tests involving the dialog components failing with the following stack:
```
info  -   Unhandled promise rejection: TypeError: this.getRootNode(...).getElementById is not a function
info  -       at Dialog.applyFocus (out/temp/karma/r205582/commons.js:520735:44)
info  -       at async Dialog.applyInitialFocus (out/temp/karma/r205582/commons.js:520722:9)
info  -       at async Dialog._open (out/temp/karma/r205582/commons.js:520783:13)
info  -       at async Dialog.show (out/temp/karma/r205582/commons.js:513719:9)
```
most impacted tests basically
- change the language 
- render a ui5Dialog (which specifies an initialFocus control)

The two following experiments that solved the issue and hopefully may provide you with more insight about what's wrong with either the production code or the test scenario:
- undoing the fix introduced by https://github.com/SAP/ui5-webcomponents/pull/6912
- conditionally invoking the `this.getRootNode().getElementById`

### Affected Component

Popup-like Components (Dialog, Menu)

### Expected Behaviour

No exception thrown at Dialog.show/showAt or Menu.show/showAt

### Log Output, Stack Trace or Screenshots

info  karma -   Unhandled promise rejection: TypeError: this.getRootNode(...).getElementById is not a function
info  karma -       at Dialog.applyFocus (out/temp/karma/r205582/commons.js:520735:44)
info  karma -       at async Dialog.applyInitialFocus (out/temp/karma/r205582/commons.js:520722:9)
info  karma -       at async Dialog._open (out/temp/karma/r205582/commons.js:520783:13)
info  karma -       at async Dialog.show (out/temp/karma/r205582/commons.js:513719:9)

### Priority

High

### UI5 Web Components Version

v1.13.0

### Browser

Chrome

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
@louologuem can you add the code of the test that fails to have a look at you set up - to understand the test frameworks that you use.
